CREATE TABLE LOCALITA (
    id_localita INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    localita VARCHAR(255) NOT NULL
);

CREATE TABLE CATEGORIA (
    id_categoria INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria VARCHAR(255) NOT NULL
);

CREATE TABLE EVENTI (
    id_evento INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_categoria INT,
    id_localita INT,
    nome VARCHAR(255),
    descrizione VARCHAR(255) NOT NULL,
    inizio TIMESTAMP NOT NULL,
    fine TIMESTAMP NOT NULL,
    totale_poltrona INT NOT NULL,
    disponibilita_poltrona INT NOT NULL,
    totale_in_piedi INT NOT NULL,
    disponibilita_in_piedi INT NOT NULL,
    prezzi_poltrona DECIMAL(10, 2) NOT NULL,
    prezzi_in_piedi DECIMAL(10, 2) NOT NULL,
    n_click INT DEFAULT 0,
    image_name VARCHAR(255),
    FOREIGN KEY (id_localita) REFERENCES LOCALITA(id_localita),
    FOREIGN KEY (id_categoria) REFERENCES CATEGORIA(id_categoria) 
);

CREATE TABLE SCONTI_EVENTO (
    id_sconto INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_evento INT,
    data_scadenza DATE NOT NULL,
    sconto DECIMAL(5, 2) NOT NULL,
    FOREIGN KEY (id_evento) REFERENCES EVENTI(id_evento) ON DELETE CASCADE
);

CREATE TABLE UTENTI (
    id_utente INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    cognome VARCHAR(255) NOT NULL,
    data_nascita DATE NOT NULL,
    email VARCHAR(255) NOT NULL,
    telefono CHAR(10) NOT NULL,
    n_acquisti INT DEFAULT 0,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE PRENOTAZIONE_BIGLIETTI (
    id_prenotazione INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_evento INT NOT NULL,
    id_utente INT,
    id_sconto INT,
    quantita_poltrona INT DEFAULT 0,
    quantita_in_piedi INT DEFAULT 0,
    data_acquisto TIMESTAMP NOT NULL,
    prezzo DECIMAL (10, 2) NOT NULL,
    FOREIGN KEY (id_evento) REFERENCES EVENTI(id_evento) ON DELETE CASCADE,
    FOREIGN KEY (id_utente) REFERENCES UTENTI(id_utente) ON DELETE SET NULL,
    FOREIGN KEY (id_sconto) REFERENCES SCONTI_EVENTO(id_sconto) ON DELETE CASCADE
);


CREATE TABLE AMMINISTRATORI (
    id_amministratore INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);

INSERT INTO LOCALITA (localita) VALUES ('Trento');
INSERT INTO LOCALITA (localita) VALUES ('Povo');
INSERT INTO LOCALITA (localita) VALUES ('Rovereto');
INSERT INTO LOCALITA (localita) VALUES ('Riva del Garda');
INSERT INTO LOCALITA (localita) VALUES ('Arco');

INSERT INTO CATEGORIA (categoria) VALUES ('concerti');
INSERT INTO CATEGORIA (categoria) VALUES ('spettacoli teatrali');
INSERT INTO CATEGORIA (categoria) VALUES ('eventi sportivi');
INSERT INTO CATEGORIA (categoria) VALUES ('visite guidate a mostre');
INSERT INTO CATEGORIA (categoria) VALUES ('visite guidate a musei');

INSERT INTO EVENTI (
    id_categoria,
    id_localita,
    nome,
    descrizione,
    inizio,
    fine,
    totale_poltrona,
    disponibilita_poltrona,
    totale_in_piedi,
    disponibilita_in_piedi,
    prezzi_poltrona,
    prezzi_in_piedi,
    n_click,
    image_name
) VALUES (
    1,
    1,
    'Concerto di Rock',
    'Un evento musicale imperdibile con band rock famose.',
    '2024-08-10 21:00:00',
    '2024-08-10 23:00:00',
    100,
    50,
    200,
    150,
    30.00,
    15.00,
    100,
    'generico.jpg'
);

INSERT INTO EVENTI (
    id_categoria,
    id_localita,
    nome,
    descrizione,
    inizio,
    fine,
    totale_poltrona,
    disponibilita_poltrona,
    totale_in_piedi,
    disponibilita_in_piedi,
    prezzi_poltrona,
    prezzi_in_piedi,
    n_click,
    image_name
) VALUES (
    2,
    2,
    'Spettacolo Teatrale',
    'Un coinvolgente spettacolo teatrale con performance straordinarie.',
    '2024-09-05 20:00:00',
    '2024-09-05 22:00:00',
    80,
    30,
    100,
    80,
    25.00,
    10.00,
    200,
    'generico.jpg'
);

INSERT INTO EVENTI (
    id_categoria,
    id_localita,
    nome,
    descrizione,
    inizio,
    fine,
    totale_poltrona,
    disponibilita_poltrona,
    totale_in_piedi,
    disponibilita_in_piedi,
    prezzi_poltrona,
    prezzi_in_piedi,
    n_click,
    image_name
) VALUES (
    1,
    1,
    'Concerto di Jazz',
    'Una serata di musica jazz con artisti internazionali.',
    '2024-09-15 20:00:00',
    '2024-09-15 23:00:00',
    150,
    70,
    250,
    180,
    35.00,
    18.00,
    75,
    'generico.jpg'
);


INSERT INTO EVENTI (
    id_categoria,
    id_localita,
    nome,
    descrizione,
    inizio,
    fine,
    totale_poltrona,
    disponibilita_poltrona,
    totale_in_piedi,
    disponibilita_in_piedi,
    prezzi_poltrona,
    prezzi_in_piedi,
    n_click,
    image_name
) VALUES (
    2,
    3,
    'Commedia dell`Arte',
    'Un esilarante spettacolo di commedia dell`arte con attori professionisti.',
    '2024-10-10 19:30:00',
    '2024-10-10 21:30:00',
    100,
    50,
    120,
    90,
    20.00,
    12.00,
    90,
    'generico.jpg'
);

INSERT INTO EVENTI (
    id_categoria,
    id_localita,
    nome,
    descrizione,
    inizio,
    fine,
    totale_poltrona,
    disponibilita_poltrona,
    totale_in_piedi,
    disponibilita_in_piedi,
    prezzi_poltrona,
    prezzi_in_piedi,
    n_click,
    image_name
) VALUES (
    3,
    4,
    'Partita di Calcio',
    'Una sfida emozionante tra le migliori squadre locali.',
    '2024-08-20 18:00:00',
    '2024-08-20 20:00:00',
    500,
    0,
    1000,
    0,
    40.00,
    25.00,
    200,
    'generico.jpg'
);

INSERT INTO EVENTI (
    id_categoria,
    id_localita,
    nome,
    descrizione,
    inizio,
    fine,
    totale_poltrona,
    disponibilita_poltrona,
    totale_in_piedi,
    disponibilita_in_piedi,
    prezzi_poltrona,
    prezzi_in_piedi,
    n_click,
    image_name
) VALUES (
    4,
    5,
    'Mostra d`Arte Moderna',
    'Una visita guidata attraverso le più recenti opere di arte moderna.',
    '2024-08-25 10:00:00',
    '2024-08-25 12:00:00',
    50,
    25,
    0,
    0,
    15.00,
    0.00,
    60,
    'generico.jpg'
);

INSERT INTO EVENTI (
    id_categoria,
    id_localita,
    nome,
    descrizione,
    inizio,
    fine,
    totale_poltrona,
    disponibilita_poltrona,
    totale_in_piedi,
    disponibilita_in_piedi,
    prezzi_poltrona,
    prezzi_in_piedi,
    n_click,
    image_name
) VALUES (
    5, 
    2,
    'Tour del Museo di Storia Naturale',
    'Una visita guidata al museo con focus sulle esposizioni di storia naturale.',
    '2024-09-20 14:00:00',
    '2024-09-20 16:00:00',
    40, 
    20,  
    0,   
    0,   
    12.00, 
    0.00,  
    45,
    'generico.jpg'
);

INSERT INTO EVENTI (
    id_categoria,
    id_localita,
    nome,
    descrizione,
    inizio,
    fine,
    totale_poltrona,
    disponibilita_poltrona,
    totale_in_piedi,
    disponibilita_in_piedi,
    prezzi_poltrona,
    prezzi_in_piedi,
    n_click,
    image_name
) VALUES (
    1, 
    3,
    'Concerto di Jazz`s Delight',
    'Un evento esclusivo con alcuni dei migliori artisti jazz internazionali.',
    '2024-10-15 20:00:00',
    '2024-10-15 23:00:00',
    150,
    0,  
    300, 
    0,
    35.00, 
    20.00,
    150,
    'generico.jpg'
);


INSERT INTO EVENTI (
    id_categoria,
    id_localita,
    nome,
    descrizione,
    inizio,
    fine,
    totale_poltrona,
    disponibilita_poltrona,
    totale_in_piedi,
    disponibilita_in_piedi,
    prezzi_poltrona,
    prezzi_in_piedi,
    n_click,
    image_name
) VALUES (
    2, 
    1, 
    'Teatro dell`Assurdo',
    'Una commedia teatrale esilarante e surreale che esplora l`assurdo della vita.',
    '2024-11-01 21:00:00',
    '2024-11-01 23:00:00',
    100, 
    50,  
    0,  
    0,   
    28.00, 
    0.00,  
    180,
    'generico.jpg'
);

INSERT INTO EVENTI (
    id_categoria,
    id_localita,
    nome,
    descrizione,
    inizio,
    fine,
    totale_poltrona,
    disponibilita_poltrona,
    totale_in_piedi,
    disponibilita_in_piedi,
    prezzi_poltrona,
    prezzi_in_piedi,
    n_click,
    image_name
) VALUES (
    3,
    2, 
    'Maratona di Povo',
    'Una maratona annuale che attira corridori da tutto il mondo.',
    '2024-12-01 09:00:00',
    '2024-12-01 15:00:00',
    500, 
    200, 
    1000, 
    800, 
    40.00, 
    20.00, 
    300 ,
    'generico.jpg'
);

INSERT INTO EVENTI (
    id_categoria,
    id_localita,
    nome,
    descrizione,
    inizio,
    fine,
    totale_poltrona,
    disponibilita_poltrona,
    totale_in_piedi,
    disponibilita_in_piedi,
    prezzi_poltrona,
    prezzi_in_piedi,
    n_click,
    image_name
) VALUES (
    4,
    4,
    'Mostra di Arte Moderna',
    'Una visita guidata alla mostra di arte moderna con opere di artisti contemporanei.',
    '2024-10-20 10:00:00',
    '2024-10-20 12:00:00',
    80, 
    40,  
    0,   
    0,   
    25.00, 
    0.00,  
    90 ,
    'generico.jpg'
);

INSERT INTO EVENTI (
    id_categoria,
    id_localita,
    nome,
    descrizione,
    inizio,
    fine,
    totale_poltrona,
    disponibilita_poltrona,
    totale_in_piedi,
    disponibilita_in_piedi,
    prezzi_poltrona,
    prezzi_in_piedi,
    n_click,
    image_name
) VALUES (
    5, 
    5, 
    'Visita al Museo d`Arte Antica',
    'Esplora una collezione di arte antica con una guida esperta.',
    '2024-11-10 11:00:00',
    '2024-11-10 13:00:00',
    50, 
    20,  
    0,   
    0,   
    18.00, 
    0.00,  
    60 ,
    'generico.jpg'
);

INSERT INTO EVENTI (
    id_categoria,
    id_localita,
    nome,
    descrizione,
    inizio,
    fine,
    totale_poltrona,
    disponibilita_poltrona,
    totale_in_piedi,
    disponibilita_in_piedi,
    prezzi_poltrona,
    prezzi_in_piedi,
    n_click,
    image_name
) VALUES (
    1, 
    5, 
    'Concerto di Musica Classica',
    'Un concerto di musica classica con un ensemble di musicisti di fama.',
    '2024-12-15 20:00:00',
    '2024-12-15 22:00:00',
    120,
    60,  
    0,  
    0,   
    50.00, 
    0.00,  
    130,
    'generico.jpg'
);



INSERT INTO SCONTI_EVENTO (
    id_evento,
    data_scadenza,
    sconto
) VALUES (
    1, 
    '2024-12-09',
    10.00 
);

INSERT INTO SCONTI_EVENTO (
    id_evento,
    data_scadenza,
    sconto
) VALUES (
    2, 
    '2024-09-04',
    15.00 
);

INSERT INTO SCONTI_EVENTO (
    id_evento,
    data_scadenza,
    sconto
) VALUES (
    4, 
    '2025-03-08',
    15.00 
);

INSERT INTO SCONTI_EVENTO (
    id_evento,
    data_scadenza,
    sconto
) VALUES (
    3, 
    '2025-01-14',
    15.00 
);

INSERT INTO UTENTI (
    nome,
    cognome,
    data_nascita,
    email,
    telefono,
    n_acquisti,
    username,
    password
) VALUES (
    'Mario',
    'Rossi',
    '1990-01-15',
    'mario.rossi@example.com',
    '3456789012',
    5,
    'mrossi',
    'password123!'
);

INSERT INTO UTENTI (
    nome,
    cognome,
    data_nascita,
    email,
    telefono,
    n_acquisti,
    username,
    password
) VALUES (
    'Giulia',
    'Bianchi',
    '1985-03-22',
    'giulia.bianchi@example.com',
    '3216549870',
    9,
    'gbianchi',
    'securepass456!'
);

INSERT INTO PRENOTAZIONE_BIGLIETTI (
    id_evento,
    id_utente,
    id_sconto,
    quantita_poltrona,
    quantita_in_piedi,
    data_acquisto,
    prezzo
) VALUES (
    1, 
    1, 
    1, 
    2,
    0, 
    '2024-08-01 10:30:00',
    54.00 
);


INSERT INTO PRENOTAZIONE_BIGLIETTI (
    id_evento,
    id_utente,
    id_sconto,
    quantita_poltrona,
    quantita_in_piedi,
    data_acquisto,
    prezzo
) VALUES (
    2, 
    2,
    2,
    0, 
    1,
    '2024-08-02 11:00:00',
    8.50
);

INSERT INTO AMMINISTRATORI (
    username,
    password
) VALUES (
    'admin',
    '01nimda!'
);