package web.example.progweb.model.entity;

/*
CREATE TABLE SCONTI_EVENTO (
    id_sconto INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_evento INT,
    data_scadenza DATE NOT NULL,
    sconto DECIMAL(5, 2) NOT NULL,
    FOREIGN KEY (id_evento) REFERENCES EVENTI(id_evento)
);
 */

import java.math.BigDecimal;

public class Discount {
    private int id_discount;
    private int id_event;
    private String expiration_date;
    private BigDecimal discount;

    public Discount(int id_discount, int id_event, String expiration_date, BigDecimal discount) {
        this.id_discount = id_discount;
        this.id_event = id_event;
        this.expiration_date = expiration_date;
        this.discount = discount;
    }

    public int getId_discount() {
        return id_discount;
    }

    public int getId_event() {
        return id_event;
    }

    public String getExpiration_date() {
        return expiration_date;
    }

    public BigDecimal getDiscount() {
        return discount;
    }
}
