package web.example.progweb.model.entity;

/*
CREATE TABLE EVENTI (
    id_evento INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_categoria INT,
    id_localita INT,
    nome VARCHAR(255) NOT NULL,
    inizio TIMESTAMP NOT NULL,
    fine TIMESTAMP NOT NULL,
    totale_poltrona INT NOT NULL,
    disponibilita_poltrona INT NOT NULL,
    totale_in_piedi INT NOT NULL,
    disponibilita_in_piedi INT NOT NULL,
    prezzi_poltrona DECIMAL(10, 2) NOT NULL,
    prezzi_in_piedi DECIMAL(10, 2) NOT NULL,
    n_click INT DEFAULT 0,
    FOREIGN KEY (id_localita) REFERENCES LOCALITA(id_localita),
    FOREIGN KEY (id_categoria) REFERENCES CATEGORIA(id_categoria)
);
 */

import java.math.BigDecimal;

public class Event {
    private final int id;
    private final int idCategory;
    private final int idLocation;
    private final String name;
    private final String start;
    private final String end;
    private final int totalSeats;
    private final int availableSeats;
    private final int totalStanding;
    private final int availableStanding;
    private final BigDecimal seatPrice;
    private final BigDecimal standingPrice;
    private final int nClick;

    public Event (int id, int idCategory, int idLocation, String name, String start, String end, int totalSeats, int availableSeats, int totalStanding, int availableStanding, BigDecimal seatPrice, BigDecimal standingPrice, int nClick) {
        this.id = id;
        this.idCategory = idCategory;
        this.idLocation = idLocation;
        this.name = name;
        this.start = start;
        this.end = end;
        this.totalSeats = totalSeats;
        this.availableSeats = availableSeats;
        this.totalStanding = totalStanding;
        this.availableStanding = availableStanding;
        this.seatPrice = seatPrice;
        this.standingPrice = standingPrice;
        this.nClick = nClick;
    }

    public int getId() {
        return id;
    }

    public int getIdCategory() {
        return idCategory;
    }

    public int getnClick() {
        return nClick;
    }

    public int getIdLocation() {
        return idLocation;
    }

    public String getName() {
        return name;
    }

    public String getStart() {
        return start;
    }

    public String getEnd() {
        return end;
    }

    public int getTotalSeats() {
        return totalSeats;
    }

    public int getAvailableSeats() {
        return availableSeats;
    }

    public int getTotalStanding() {
        return totalStanding;
    }

    public int getAvailableStanding() {
        return availableStanding;
    }

    public BigDecimal getSeatPrice() {
        return seatPrice;
    }

    public BigDecimal getStandingPrice() {
        return standingPrice;
    }

    @Override
    public String toString() {
        return "Event{" +
                "id='" + id + '\'' +
                ", idCategory='" + idCategory + '\'' +
                ", idLocation='" + idLocation + '\'' +
                ", name='" + name + '\'' +
                ", start='" + start + '\'' +
                ", end='" + end + '\'' +
                ", totalSeats='" + totalSeats + '\'' +
                ", availableSeats='" + availableSeats + '\'' +
                ", totalStanding='" + totalStanding + '\'' +
                ", availableStanding='" + availableStanding + '\'' +
                ", seatPrice='" + seatPrice + '\'' +
                ", standingPrice='" + standingPrice + '\'' +
                ", nClick=" + nClick +
                '}';
    }
}
