package web.example.progweb.model.entity;

/*
CREATE TABLE EVENTI (
    id_evento INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_categoria INT,
    id_localita INT,
    nome VARCHAR(255) NOT NULL,
    inizio TIMESTAMP NOT NULL,
    fine TIMESTAMP NOT NULL,
    totale_poltrona INT NOT NULL,
    disponibilita_poltrona INT NOT NULL,
    totale_in_piedi INT NOT NULL,
    disponibilita_in_piedi INT NOT NULL,
    prezzi_poltrona DECIMAL(10, 2) NOT NULL,
    prezzi_in_piedi DECIMAL(10, 2) NOT NULL,
    n_click INT DEFAULT 0,
    FOREIGN KEY (id_localita) REFERENCES LOCALITA(id_localita),
    FOREIGN KEY (id_categoria) REFERENCES CATEGORIA(id_categoria)
);
 */

public class Event {
    private final String id;
    private final String idCategory;
    private final String idLocation;
    private final String name;
    private final String start;
    private final String end;
    private final String totalSeats;
    private final String availableSeats;
    private final String totalStanding;
    private final String availableStanding;
    private final String seatPrice;
    private final String standingPrice;
    private final int nClick;

    public Event (String id, String idCategory, String idLocation, String name, String start, String end, String totalSeats, String availableSeats, String totalStanding, String availableStanding, String seatPrice, String standingPrice, int nClick) {
        this.id = id;
        this.idCategory = idCategory;
        this.idLocation = idLocation;
        this.name = name;
        this.start = start;
        this.end = end;
        this.totalSeats = totalSeats;
        this.availableSeats = availableSeats;
        this.totalStanding = totalStanding;
        this.availableStanding = availableStanding;
        this.seatPrice = seatPrice;
        this.standingPrice = standingPrice;
        this.nClick = nClick;
    }

    public String getId() {
        return id;
    }

    public String getIdCategory() {
        return idCategory;
    }

    public int getnClick() {
        return nClick;
    }

    public String getIdLocation() {
        return idLocation;
    }

    public String getName() {
        return name;
    }

    public String getStart() {
        return start;
    }

    public String getEnd() {
        return end;
    }

    public String getTotalSeats() {
        return totalSeats;
    }

    public String getAvailableSeats() {
        return availableSeats;
    }

    public String getTotalStanding() {
        return totalStanding;
    }

    public String getAvailableStanding() {
        return availableStanding;
    }

    public String getSeatPrice() {
        return seatPrice;
    }

    public String getStandingPrice() {
        return standingPrice;
    }

    @Override
    public String toString() {
        return "Event{" +
                "id='" + id + '\'' +
                ", idCategory='" + idCategory + '\'' +
                ", idLocation='" + idLocation + '\'' +
                ", name='" + name + '\'' +
                ", start='" + start + '\'' +
                ", end='" + end + '\'' +
                ", totalSeats='" + totalSeats + '\'' +
                ", availableSeats='" + availableSeats + '\'' +
                ", totalStanding='" + totalStanding + '\'' +
                ", availableStanding='" + availableStanding + '\'' +
                ", seatPrice='" + seatPrice + '\'' +
                ", standingPrice='" + standingPrice + '\'' +
                ", nClick=" + nClick +
                '}';
    }
}
