package web.example.progweb.model.entity;

/*
CREATE TABLE PRENOTAZIONE_BIGLIETTI (
    id_prenotazione INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_evento INT NOT NULL,
    id_utente INT NOT NULL,
    id_sconto INT,
    tipologia VARCHAR(10) CHECK (tipologia IN ('poltrona', 'in piedi')) NOT NULL,
    data_acquisto TIMESTAMP NOT NULL,
    FOREIGN KEY (id_evento) REFERENCES EVENTI(id_evento),
    FOREIGN KEY (id_utente) REFERENCES UTENTI(id_utente),
    FOREIGN KEY (id_sconto) REFERENCES SCONTI_EVENTO(id_sconto)
);
 */

import java.math.BigDecimal;

public class Ticket {
    private final int id_prenotazione;
    private final int id_evento;
    private final int id_utente;
    private final int id_sconto;
    private final String tipologia;
    private final String data_acquisto;
    private final BigDecimal price;


    public Ticket(int id_prenotazione, int id_evento, int id_utente, int id_sconto, String tipologia, String data_acquisto, BigDecimal price) {
        this.id_prenotazione = id_prenotazione;
        this.id_evento = id_evento;
        this.id_utente = id_utente;
        this.id_sconto = id_sconto;
        this.tipologia = tipologia;
        this.data_acquisto = data_acquisto;
        this.price = price;
    }

    public int getId_prenotazione() {
        return id_prenotazione;
    }

    public int getId_evento() {
        return id_evento;
    }

    public int getId_utente() {
        return id_utente;
    }

    public int getId_sconto() {
        return id_sconto;
    }

    public String getTipologia() {
        return tipologia;
    }

    public String getData_acquisto() {
        return data_acquisto;
    }

    public BigDecimal getPrice() {
        return price;
    }
}
