package web.example.progweb.model.entity;

/*
CREATE TABLE PRENOTAZIONE_BIGLIETTI (
    id_prenotazione INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_evento INT NOT NULL,
    id_utente INT NOT NULL,
    id_sconto INT,
    quantita INT DEFAULT 1,
    tipologia VARCHAR(10) CHECK (tipologia IN ('poltrona', 'in piedi')) NOT NULL,
    data_acquisto TIMESTAMP NOT NULL,
    prezzo DECIMAL (10, 2) NOT NULL,
    FOREIGN KEY (id_evento) REFERENCES EVENTI(id_evento) ON DELETE CASCADE,
    FOREIGN KEY (id_utente) REFERENCES UTENTI(id_utente) ON DELETE CASCADE,
    FOREIGN KEY (id_sconto) REFERENCES SCONTI_EVENTO(id_sconto) ON DELETE CASCADE
);
 */

import java.math.BigDecimal;

public class Ticket {
    private final int idPrenotazione;
    private final int idEvento;
    private final int idUtente;
    private final int idSconto;
    private final int quantita_poltrona;
    private final int quantita_in_piedi;
    private final String dataAcquisto;
    private final BigDecimal price;


    public Ticket(int id_prenotazione, int id_evento, int id_utente, int id_sconto,int quantita_poltrona, int quantita_in_piedi, String data_acquisto, BigDecimal price) {
        this.idPrenotazione = id_prenotazione;
        this.idEvento = id_evento;
        this.idUtente = id_utente;
        this.idSconto = id_sconto;
        this.quantita_poltrona = quantita_poltrona;
        this.quantita_in_piedi = quantita_in_piedi;
        this.dataAcquisto = data_acquisto;
        this.price = price;
    }

    public int idPrenotazione() {
        return idPrenotazione;
    }

    public int idEvento() {
        return idEvento;
    }

    public int idUtente() {
        return idUtente;
    }

    public int idSconto() {
        return idSconto;
    }

    public int quantita_poltrona() {
        return quantita_poltrona;
    }

    public int quantita_in_piedi() {
        return quantita_in_piedi;
    }

    public String data_acquisto() {
        return dataAcquisto;
    }

    public BigDecimal getPrice() {
        return price;
    }

    @Override
    public String toString() {
        return "Ticket{" +
                "idPrenotazione=" + idPrenotazione +
                ", idEvento=" + idEvento +
                ", idUtente=" + idUtente +
                ", idSconto=" + idSconto +
                ", quantita poltrona="+quantita_poltrona+
                ", quantita in piedi="+quantita_in_piedi+
                ", dataAcquisto='" + dataAcquisto + '\'' +
                ", price=" + price +
                '}';
    }
}
