package web.example.progweb.model.entity;

/*
CREATE TABLE PRENOTAZIONE_BIGLIETTI (
    id_prenotazione INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_evento INT NOT NULL,
    id_utente INT NOT NULL,
    id_sconto INT,
    tipologia VARCHAR(10) CHECK (tipologia IN ('poltrona', 'in piedi')) NOT NULL,
    data_acquisto TIMESTAMP NOT NULL,
    FOREIGN KEY (id_evento) REFERENCES EVENTI(id_evento),
    FOREIGN KEY (id_utente) REFERENCES UTENTI(id_utente),
    FOREIGN KEY (id_sconto) REFERENCES SCONTI_EVENTO(id_sconto)
);
 */

public class Ticket {
    private final String id_prenotazione;
    private final String id_evento;
    private final String id_utente;
    private final String id_sconto;
    private final String tipologia;
    private final String data_acquisto;

    public Ticket( String id_prenotazione, String id_evento, String id_utente, String id_sconto, String tipologia, String data_acquisto) {
        this.id_prenotazione = id_prenotazione;
        this.id_evento = id_evento;
        this.id_utente = id_utente;
        this.id_sconto = id_sconto;
        this.tipologia = tipologia;
        this.data_acquisto = data_acquisto;
    }

    public String getId_prenotazione() {
        return id_prenotazione;
    }

    public String getId_evento() {
        return id_evento;
    }

    public String getId_utente() {
        return id_utente;
    }

    public String getId_sconto() {
        return id_sconto;
    }

    public String getTipologia() {
        return tipologia;
    }

    public String getData_acquisto() {
        return data_acquisto;
    }
}
