package web.example.progweb.model;

import web.example.progweb.model.abstractClass.AbstractDAO;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/*
CREATE TABLE CATEGORIA (
    id_categoria INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria VARCHAR(255) NOT NULL
);
 */

public class CategoryDAO extends AbstractDAO {
    public CategoryDAO() throws SQLException, ClassNotFoundException {
        super();
    }

    public String getIdCategory(String category) throws SQLException {
        String query = "SELECT id_categoria FROM CATEGORIA WHERE categoria = ?";
        PreparedStatement preparedStatement = connection.prepareStatement(query);
        preparedStatement.setString(1, category);
        ResultSet resultSet = preparedStatement.executeQuery();
        if (resultSet.next()) {
            return resultSet.getString("id_categoria");
        }
        return null;
    }

    public String getCategory(String idCategory) throws SQLException {
        String query = "SELECT categoria FROM CATEGORIA WHERE id_categoria = ?";
        PreparedStatement preparedStatement = connection.prepareStatement(query);
        preparedStatement.setString(1, idCategory);
        ResultSet resultSet = preparedStatement.executeQuery();
        if (resultSet.next()) {
            return resultSet.getString("categoria");
        }
        return null;
    }


}
