package web.example.progweb.model;

import web.example.progweb.model.abstractClass.AbstractModel;
import web.example.progweb.model.entity.Discount;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/*
CREATE TABLE SCONTI_EVENTO (
    id_sconto INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_evento INT,
    data_scadenza DATE NOT NULL,
    sconto DECIMAL(5, 2) NOT NULL,
    FOREIGN KEY (id_evento) REFERENCES EVENTI(id_evento)
);
 */

public class DiscountModel extends AbstractModel {
    public DiscountModel() throws SQLException, ClassNotFoundException {
        super();
    }

    public void insertDiscount(String id_evento, String data_scadenza, double sconto) throws SQLException {
        String query = "INSERT INTO SCONTI_EVENTO (id_evento, data_scadenza, sconto) VALUES (?, ?, ?)";
        PreparedStatement preparedStatement = connection.prepareStatement(query);
        preparedStatement.setString(1, id_evento);
        preparedStatement.setString(2, data_scadenza);
        preparedStatement.setDouble(3, sconto);
        preparedStatement.executeUpdate();
    }

    public List<Discount> getValidDiscount(String id_evento) throws SQLException {
        String query = "SELECT * FROM SCONTI_EVENTO WHERE id_evento = ? AND data_scadenza >= CURRENT_DATE";
        PreparedStatement preparedStatement = connection.prepareStatement(query);
        preparedStatement.setString(1, id_evento);
        ResultSet resultSet = preparedStatement.executeQuery();

        List<Discount> validDiscounts = new ArrayList<>();
        while (resultSet.next()) {
            String idSconto = resultSet.getString("id_sconto");
            String eventId = resultSet.getString("id_evento");
            String expirationDate = resultSet.getString("data_scadenza");
            double discount = resultSet.getDouble("sconto");

            validDiscounts.add(new Discount(idSconto, eventId, expirationDate, discount));
        }
        return validDiscounts;
    }

}
