package web.example.progweb.model;


import web.example.progweb.model.abstractClass.AbstractModel;
import web.example.progweb.model.entity.Category;
import web.example.progweb.model.entity.Discount;
import web.example.progweb.model.entity.Event;
import web.example.progweb.model.entity.Location;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/*
CREATE TABLE EVENTI (
    id_evento INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_categoria INT,
    id_localita INT,
    nome VARCHAR(255) NOT NULL,
    inizio TIMESTAMP NOT NULL,
    fine TIMESTAMP NOT NULL,
    totale_poltrona INT NOT NULL,
    disponibilita_poltrona INT NOT NULL,
    totale_in_piedi INT NOT NULL,
    disponibilita_in_piedi INT NOT NULL,
    prezzi_poltrona DECIMAL(10, 2) NOT NULL,
    prezzi_in_piedi DECIMAL(10, 2) NOT NULL,
    n_click INT DEFAULT 0,
    FOREIGN KEY (id_localita) REFERENCES LOCALITA(id_localita),
    FOREIGN KEY (id_categoria) REFERENCES CATEGORIA(id_categoria)
);
 */

public class EventModel extends AbstractModel {
    private PreparedStatement getEventByCategoryPreparedStatement;
    private PreparedStatement getEventByIdPreparedStatement;
    private PreparedStatement insertEventPreparedStatement;
    private PreparedStatement deleteEventPreparedStatement;
    private PreparedStatement incrementClickPreparedStatement;
    private PreparedStatement checkIdPreparedStatement;
    private PreparedStatement deleteCategoryPreparedStatement;
    private PreparedStatement deleteLocationPreparedStatement;
    private PreparedStatement updateAvailabilityPreparedStatement;
    private PreparedStatement checkAvailabilityPreparedStatement;
    private PreparedStatement checkIdCategoryPreparedStatement;

    public EventModel() throws SQLException, ClassNotFoundException {
        super();
        prepareStatement();
    }

    public EventModel (Connection connection) throws SQLException{
        super(connection);
        prepareStatement();
    }

    private void prepareStatement ()  throws SQLException {
        getEventByCategoryPreparedStatement = connection.prepareStatement("SELECT * FROM EVENTI WHERE id_categoria = ?");
        getEventByIdPreparedStatement = connection.prepareStatement("SELECT * FROM EVENTI WHERE id_evento = ?");
        insertEventPreparedStatement = connection.prepareStatement("INSERT INTO EVENTI (id_categoria, id_localita, nome, descrizione, inizio, fine, totale_poltrona, disponibilita_poltrona, totale_in_piedi, disponibilita_in_piedi, prezzi_poltrona, prezzi_in_piedi) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", PreparedStatement.RETURN_GENERATED_KEYS);
        deleteEventPreparedStatement = connection.prepareStatement("DELETE FROM EVENTI WHERE id_evento = ?");
        checkIdPreparedStatement = connection.prepareStatement("SELECT * FROM EVENTI WHERE id_evento = ?");
        checkIdCategoryPreparedStatement = connection.prepareStatement("SELECT * FROM CATEGORIA WHERE id_categoria = ?");
        deleteCategoryPreparedStatement = connection.prepareStatement("DELETE FROM CATEGORIA WHERE id_categoria = ?");
        deleteLocationPreparedStatement = connection.prepareStatement("DELETE FROM LOCALITA WHERE id_localita = ?");
        incrementClickPreparedStatement = connection.prepareStatement("UPDATE EVENTI SET n_click = n_click + 1 WHERE id_evento = ?");

        checkAvailabilityPreparedStatement = connection.prepareStatement("SELECT disponibilita_in_piedi, disponibilita_poltrona FROM EVENTI WHERE id_evento = ?");
        updateAvailabilityPreparedStatement = connection.prepareStatement("UPDATE EVENTI SET disponibilita_poltrona = disponibilita_poltrona + ?, disponibilita_in_piedi = disponibilita_in_piedi + ? WHERE id_evento = ?");
    }

    public Event insertEvent(int idCategoria, int idLocalita, String name, String descrizione, String start, String end, int totalSeats, int availableSeats, int totalStanding, int availableStanding, BigDecimal seatPrice, BigDecimal standingPrice) throws SQLException {
        insertEventPreparedStatement.setInt(1, idCategoria);
        insertEventPreparedStatement.setInt(2, idLocalita);
        insertEventPreparedStatement.setString(3, name);
        insertEventPreparedStatement.setString(4, descrizione);
        insertEventPreparedStatement.setString(5, formatDateTime(start));
        insertEventPreparedStatement.setString(6, formatDateTime(end));
        insertEventPreparedStatement.setInt(7, totalSeats);
        insertEventPreparedStatement.setInt(8, availableSeats);
        insertEventPreparedStatement.setInt(9, totalStanding);
        insertEventPreparedStatement.setInt(10, availableStanding);
        insertEventPreparedStatement.setBigDecimal(11, seatPrice);
        insertEventPreparedStatement.setBigDecimal(12, standingPrice);
        int affectedRows = insertEventPreparedStatement.executeUpdate();
        if (affectedRows > 0){
            try (ResultSet generatedKeys = insertEventPreparedStatement.getGeneratedKeys()) {
                if (generatedKeys.next()) {
                    return getEventById(generatedKeys.getInt(1));
                }
            }
        }
        return null;
    }

    public void deleteEvent(int id) throws SQLException {
        deleteEventPreparedStatement.setInt(1, id);
        deleteEventPreparedStatement.executeUpdate();
    }

    public void incrementClick(int id) throws SQLException {
        incrementClickPreparedStatement.setInt(1, id);
        incrementClickPreparedStatement.executeUpdate();
    }

    public boolean checkId (int id) throws SQLException {
        checkIdPreparedStatement.setInt(1, id);
        ResultSet resultSet = checkIdPreparedStatement.executeQuery();
        return resultSet.next();
    }

    public boolean checkCategoryId(int id) throws SQLException{ // da rivedere se funziona
        checkIdCategoryPreparedStatement.setInt(1, id);
        ResultSet resultSet = checkIdCategoryPreparedStatement.executeQuery();
        return resultSet.next();
    }

    public void deleteLocation (int id) throws SQLException {
        deleteLocationPreparedStatement.setInt(1, id);
        deleteLocationPreparedStatement.executeUpdate();
    }

    public void deleteCategory (int id) throws SQLException {
        deleteCategoryPreparedStatement.setInt(1, id);
        deleteCategoryPreparedStatement.executeUpdate();
    }

    public List<Event> getEvents() throws SQLException {
        String query = "SELECT * FROM EVENTI";
        ResultSet resultSet = unsafeExecuteQuery(query);
        List<Event> events = new ArrayList<>();
        while (resultSet.next()){
            Event event = new Event(
                    resultSet.getInt("id_evento"),
                    resultSet.getInt("id_categoria"),
                    resultSet.getInt("id_localita"),
                    resultSet.getString("nome"),
                    resultSet.getString("descrizione"),
                    resultSet.getString("inizio"),
                    resultSet.getString("fine"),
                    resultSet.getInt("totale_poltrona"),
                    resultSet.getInt("disponibilita_poltrona"),
                    resultSet.getInt("totale_in_piedi"),
                    resultSet.getInt("disponibilita_in_piedi"),
                    resultSet.getBigDecimal("prezzi_poltrona"),
                    resultSet.getBigDecimal("prezzi_in_piedi"),
                    resultSet.getInt("n_click")
            );
            events.add(event);
        }
        return events;
    }

    public List<Event> getEventByCategory(int idCategoria) throws SQLException {
        getEventByCategoryPreparedStatement.setInt(1, idCategoria);
        ResultSet resultSet = getEventByCategoryPreparedStatement.executeQuery();
        List<Event> events = new ArrayList<>();
        while (resultSet.next()) {
            Event event = new Event(
                    resultSet.getInt("id_evento"),
                    resultSet.getInt("id_categoria"),
                    resultSet.getInt("id_localita"),
                    resultSet.getString("nome"),
                    resultSet.getString("descrizione"),
                    resultSet.getString("inizio"),
                    resultSet.getString("fine"),
                    resultSet.getInt("totale_poltrona"),
                    resultSet.getInt("disponibilita_poltrona"),
                    resultSet.getInt("totale_in_piedi"),
                    resultSet.getInt("disponibilita_in_piedi"),
                    resultSet.getBigDecimal("prezzi_poltrona"),
                    resultSet.getBigDecimal("prezzi_in_piedi"),
                    resultSet.getInt("n_click")
            );
            events.add(event);
        }
        return events;
    }

    public Event getEventById (int id) throws SQLException {
        getEventByIdPreparedStatement.setInt(1, id);
        ResultSet resultSet = getEventByIdPreparedStatement.executeQuery();
        if (resultSet.next()) {
            return new Event(
                    resultSet.getInt("id_evento"),
                    resultSet.getInt("id_categoria"),
                    resultSet.getInt("id_localita"),
                    resultSet.getString("nome"),
                    resultSet.getString("descrizione"),
                    resultSet.getString("inizio"),
                    resultSet.getString("fine"),
                    resultSet.getInt("totale_poltrona"),
                    resultSet.getInt("disponibilita_poltrona"),
                    resultSet.getInt("totale_in_piedi"),
                    resultSet.getInt("disponibilita_in_piedi"),
                    resultSet.getBigDecimal("prezzi_poltrona"),
                    resultSet.getBigDecimal("prezzi_in_piedi"),
                    resultSet.getInt("n_click")
            );
        }
        return null;
    }

    public List<Event> get3MostClickedEvent() throws SQLException{
        String query = "SELECT * FROM EVENTI ORDER BY n_click DESC FETCH FIRST 3 ROWS ONLY";
        ResultSet resultSet = unsafeExecuteQuery(query);
        List<Event> events = new ArrayList<>();
        while (resultSet.next()) {
            Event event = new Event(
                    resultSet.getInt("id_evento"),
                    resultSet.getInt("id_categoria"),
                    resultSet.getInt("id_localita"),
                    resultSet.getString("nome"),
                    resultSet.getString("descrizione"),
                    resultSet.getString("inizio"),
                    resultSet.getString("fine"),
                    resultSet.getInt("totale_poltrona"),
                    resultSet.getInt("disponibilita_poltrona"),
                    resultSet.getInt("totale_in_piedi"),
                    resultSet.getInt("disponibilita_in_piedi"),
                    resultSet.getBigDecimal("prezzi_poltrona"),
                    resultSet.getBigDecimal("prezzi_in_piedi"),
                    resultSet.getInt("n_click")
            );
            events.add(event);
        }
        return events;
    }

    public List<Event> getEventsOrderedByClick() throws SQLException {
        String query = "SELECT * FROM EVENTI ORDER BY n_click DESC";
        ResultSet resultSet = unsafeExecuteQuery(query);
        List<Event> events = new ArrayList<>();
        while (resultSet.next()) {
            Event event = new Event(
                    resultSet.getInt("id_evento"),
                    resultSet.getInt("id_categoria"),
                    resultSet.getInt("id_localita"),
                    resultSet.getString("nome"),
                    resultSet.getString("descrizione"),
                    resultSet.getString("inizio"),
                    resultSet.getString("fine"),
                    resultSet.getInt("totale_poltrona"),
                    resultSet.getInt("disponibilita_poltrona"),
                    resultSet.getInt("totale_in_piedi"),
                    resultSet.getInt("disponibilita_in_piedi"),
                    resultSet.getBigDecimal("prezzi_poltrona"),
                    resultSet.getBigDecimal("prezzi_in_piedi"),
                    resultSet.getInt("n_click")
            );
            events.add(event);
        }
        return events;
    }

    public List<Category> getAllCategory() throws SQLException {
        String query = "SELECT * FROM CATEGORIA";
        ResultSet resultSet = unsafeExecuteQuery(query);
        List<Category> categories = new ArrayList<>();
        while (resultSet.next()) {
            Category category = new Category(
                    resultSet.getInt("id_categoria"),
                    resultSet.getString("categoria")
            );
            categories.add(category);
        }
        return categories;
    }

    public List<Location> getAllLocation() throws SQLException {
        String query = "SELECT * FROM LOCALITA";
        ResultSet resultSet = unsafeExecuteQuery(query);
        List<Location> locations = new ArrayList<>();
        while (resultSet.next()) {
            Location location = new Location(
                    resultSet.getInt("id_localita"),
                    resultSet.getString("localita")
            );
            locations.add(location);
        }
        return locations;
    }

    public boolean decrementAvailability(int id_event, int n_seats, int n_stands) throws SQLException {
        // Check if the requested quantities are valid and available
        if (n_seats >= 0 && n_stands >= 0 && checkAvailability(id_event, n_seats, n_stands)) {
            // Set the parameters for the update statement
            n_seats *= -1;
            n_stands *= -1;
            updateAvailabilityPreparedStatement.setInt(1, n_seats);
            updateAvailabilityPreparedStatement.setInt(2, n_stands);
            updateAvailabilityPreparedStatement.setInt(3, id_event);

            // Execute the update statement
            int rowsAffected = updateAvailabilityPreparedStatement.executeUpdate();

            // Check if the update was successful
            return rowsAffected > 0;
        }
        // Return false if the availability check fails or quantities are invalid
        return false;
    }

    public void incrementAvailability(int id_event, int n_seats, int n_stands) throws SQLException {
        if (n_seats >= 0 && n_stands >= 0){
            updateAvailabilityPreparedStatement.setInt(1,n_seats);
            updateAvailabilityPreparedStatement.setInt(2,n_stands);
            updateAvailabilityPreparedStatement.setInt(3, id_event);
            updateAvailabilityPreparedStatement.executeUpdate();
        }
    }

    public boolean checkAvailability(int id_event, int n_seats, int n_stands) throws SQLException {
        // Set the event ID parameter in the prepared statement
        checkAvailabilityPreparedStatement.setInt(1, id_event);

        // Execute the query and process the result
        try (ResultSet resultSet = checkAvailabilityPreparedStatement.executeQuery()) {
            if (resultSet.next()) {
                // Retrieve availability values from the result set
                int availableSeats = resultSet.getInt("disponibilita_poltrona");
                int availableStanding = resultSet.getInt("disponibilita_in_piedi");

                // Check if there are enough seats and standing places available
                return availableSeats >= n_seats && availableStanding >= n_stands;
            }
            // If no results are found for the given event ID, return false
            return false;
        }
    }
}
