package web.example.progweb.model;

import web.example.progweb.model.abstractClass.AbstractDAO;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/*
CREATE TABLE LOCALITA (
    id_localita INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    localita VARCHAR(255) NOT NULL
);
 */

public class LocationDAO extends AbstractDAO {
    public LocationDAO() throws SQLException, ClassNotFoundException {
        super();
    }

    public String getIdLocation(String location) throws SQLException {
        String query = "SELECT id_localita FROM LOCALITA WHERE localita = ?";
        PreparedStatement preparedStatement = connection.prepareStatement(query);
        preparedStatement.setString(1, location);
        ResultSet resultSet = preparedStatement.executeQuery();
        if (resultSet.next()) {
            return resultSet.getString("id_localita");
        }
        return null;
    }

    public String getLocation(String idLocation) throws SQLException {
        String query = "SELECT localita FROM LOCALITA WHERE id_localita = ?";
        PreparedStatement preparedStatement = connection.prepareStatement(query);
        preparedStatement.setString(1, idLocation);
        ResultSet resultSet = preparedStatement.executeQuery();
        if (resultSet.next()) {
            return resultSet.getString("localita");
        }
        return null;
    }
}
